# Find all the available rules by running:
# swiftlint rules

disabled_rules: # rule identifiers to exclude from running
   - line_length
   - function_body_length
   - todo
   - nesting
   - identifier_name
   - type_name
   - multiple_closures_with_trailing_closure
   - large_tuple
   - file_length
   - trailing_whitespace
   - statement_position
   - unused_optional_binding
   - discouraged_direct_init
opt_in_rules: # some rules are only opt-in
   # empty_count
   # - missing_docs
   # - cyclomatic_complexity
whitelist_rules:
excluded: # paths to ignore during linting. Takes precedence over `included`.
   - Carthage
   - Pods
   - Libs
   - Build
# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: warning # implicitly
force_try:
   severity: warning # explicitly
# rules that have both warning and error levels, can set just the warning level
# implicitly
# line_length: 150
# they can set both implicitly with an array
type_body_length:
   - 300 # warning
   - 400 # error
# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
#type_name:
#   min_length: 4 # only warning
#   max_length: 50 # warning and error
#   warning: 40
#   error: 50
#   excluded: iPhone # excluded via string
identifier_name:
   max_length: 60 # warning and error
   warning: 50
function_parameter_count:
   warning: 8
   error: 10
# cyclomatic_complexity:
#     warning: 2
#     error: 6
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle)
